[package]
name = "sf_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sf_core = { path = "../core" }
sf_variant = { path = "../variant" }
sf_engine = { path = "../engine" }
wasm-bindgen = "0.2"
serde = { version = "1", features = ["derive"] }
